### ISSUE TITLE
Running tests (Linux)

### ISSUE THREAD

**Issue by Frikki** [dekujs/deku#138]
I want to share my experience with running `deku` tests. This is after download and `npm install`.

```
$ make test-phantom
Cannot find phantomjs. Make sure it's in your $PATH, or specify with --phantomjs.
Error: Exit 1

make: *** [test-phantom] Error 1
```

So, let’s try to install PhantomJS globally. (bad requirement!)

```
npm install phantom
npm WARN package.json bfc@0.3.1 No repository field.
 
> weak@0.4.1 install /deku/node_modules/phantom/node_modules/dnode/node_modules/weak
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:412:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:302:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 3.13.0-52-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /deku/node_modules/phantom/node_modules/dnode/node_modules/weak
gyp ERR! node -v v1.8.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing weak@0.4.1
phantom@0.7.2 node_modules/phantom
├── win-spawn@2.0.0
├── traverse@0.6.6
├── shoe@0.0.15 (sockjs@0.3.7)
└── dnode@1.2.1 (jsonify@0.0.0, dnode-protocol@0.2.2)
```

Well, that didn’t work. So, let’s try to install it as a Linux package.

```
sudo apt-get install phantomjs
```

Finally, we can run `make test-phantom`

**Comment by anthonyshort** [comment]
Phantom is a tricky case. I usually prefer to just expect it to exist already. I opened a PR with this fixed in it. I'm curious to see what other people think about it too. 

cc @lancejpollard @stevenmiller888 @dominicbarnes

**Comment by lancejpollard** [comment]
Awesome. Yeah if a newcomer can just type a single command and it works then that is the best. Otherwise they have to learn the internals and it's very discouraging. Making as few assumptions as possible would be helpful I think.
